import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./components/layout/nav-bar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <div className="flex min-h-screen w-full">
          <aside
            className="relative flex flex-col items-center justify-start"
            style={{ width: '15vw', minWidth: 120, maxWidth: 320 }}
          >
            <div className="w-full h-full relative">
              <NavBar />
            </div>
          </aside>
          <main
            className="flex-1 flex justify-center items-start"
            style={{ width: '60vw', minWidth: 240, maxWidth: 1200 }}
          >
            <div
              className="w-full max-w-3xl flex flex-col items-center"
              style={{ marginTop: '10vh' }}
            >
              {children}
            </div>
          </main>
          <aside
            className="flex flex-col items-center justify-center"
            style={{ width: '25vw', minWidth: 120, maxWidth: 400 }}
          >
            <button className="p-4 rounded bg-gray-200 hover:bg-gray-300 mt-8">Placeholder</button>
          </aside>
        </div>
      </body>
    </html>
  );
}
