import type { Metadata } from "next";
import Link from "next/link";
import "./globals.css";
import NavBar from "./components/layout/nav-bar";
import ThemeToggle from "./components/ui/theme-toggle";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <div className="flex min-h-screen w-full">
          <aside
            className="relative"
            style={{ width: '15vw', minWidth: 120, maxWidth: 320 }}
          >
            <div className="sticky top-0 w-full">
              <div className="flex flex-col h-[100vh]">
                <NavBar />
                <div className="mt-auto w-full px-6 pt-2 pb-6">
                  <ThemeToggle />
                </div>
              </div>
            </div>
          </aside>
          <main
            className="flex-1 flex justify-center items-start"
            style={{ width: '65vw', minWidth: 240, maxWidth: 1200 }}
          >
            <div
              className="w-full max-w-3xl flex flex-col items-center"
              style={{ margin:'5vh 3vw 5vh 3vw' }}
            >
              {children}
            </div>
          </main>
          <aside
            className="flex flex-col items-center justify-center"
            style={{ width: '20vw', minWidth: 120, maxWidth: 400 }}
          >
            <button className="p-4 rounded bg-gray-200 hover:bg-gray-300 mt-8">Placeholder</button>
          </aside>
        </div>
      </body>
    </html>
  );
}
